"""Add description to books

Revision ID: 185da2e07d1f
Revises: 41211e8727b7
Create Date: 2025-04-18 12:09:19.858733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185da2e07d1f'
down_revision = '41211e8727b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
