"""Add publisher and year fields to Book

Revision ID: 41211e8727b7
Revises: c69945785ecb
Create Date: 2025-02-21 13:32:57.733459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41211e8727b7'
down_revision = 'c69945785ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
