"""Recreating all tables

Revision ID: afb8ae6aa1ed
Revises: d23c379fa8dd
Create Date: 2025-02-19 19:03:29.697149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afb8ae6aa1ed'
down_revision = 'd23c379fa8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('isbn')
        batch_op.drop_column('year')
        batch_op.drop_column('publisher')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('publisher', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_index('isbn', ['isbn'], unique=True)

    # ### end Alembic commands ###
