"""Add image_url to books

Revision ID: dd583ea51dbe
Revises: 185da2e07d1f
Create Date: 2025-04-18 12:21:21.782921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd583ea51dbe'
down_revision = '185da2e07d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
